@echo off
rem
rem Environment setup script generated by cscript configure.vbs --with-mingw-w64=\sandbox\work\mingw64 --with-openssl=\sandbox\work\OpenSSL --with-libcurl=\sandbox\work\curl\lib "--with-VC=\Program Files (x86)\Microsoft Visual Studio 10.0\VC" --with-python=\sandbox\Python27
rem
set KBUILD_PATH=C:/sandbox/work/repos/github/virtualbox/kBuild
set PATH=C:/sandbox/work/repos/github/virtualbox/kBuild/bin/win.x86;%PATH%
set PATH=%PATH%;C:\sandbox\work\repos\github\virtualbox/tools/win.amd64/bin;
